stateDiagram
    [*] --> Menu : Power on
    Menu --> Training
    Menu --> Start_Game
    Menu --> Hi_score_view

    Training --> Menu : Die


    Start_Game --> Level_1 : Delay
    Level_1 --> Level_2 : Win
    Level_2 --> Level_3 : Win
    

    Level_1 --> Hi_score_input : Die
    Level_2 --> Hi_score_input : Die
    Level_3 --> Hi_score_input : Die/Win

    Hi_score_input --> Hi_score_view

    Hi_score_view --> Menu