stateDiagram
    [*] --> start
    %%Background/pipes etc start moving

    start --> fall
    fall --> jump : btn
    jump --> fall : x time

    fall --> collide : pipe/ground hit
    jump --> collide : pipe/ground hit
    jump --> win : all pipes crossed
    fall --> win : all pipes crossed

    collide --> start : lives left
    collide --> Dead : out of lives
   